# Generated by Django 5.2.17 on 2026-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tag',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner'), ('lead', 'Lead')], max_length=20),
        ),
    ]
